# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install the Node.js dependencies
RUN npm install --production

# Copy the rest of your application files
COPY . .

# Expose the port that your app will run on
EXPOSE 3000

# Start the application
CMD [ "node", "server.js" ]
