FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /
COPY src src
COPY pom.xml pom.xml
RUN mvn clean install -Dmaven.test.skip=true

FROM openjdk:17.0
LABEL "com.siemens.customerapi"="customerapi"
LABEL version=1.0-SNAPSHOT
COPY --from=build target/customerapi-0.0.1-SNAPSHOT.jar customerapi-0.0.1-SNAPSHOT.jar
EXPOSE 7076
ENTRYPOINT ["java","-jar","customerapi-0.0.1-SNAPSHOT.jar"]